{% set name = "napari-tissuumaps" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b53e77e272b81115d311292d7b3c3e4a95a09e1a1313f4cb08dc9e9212833523

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7

test:
  imports:
    - napari_tissuumaps
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TissUUmaps/napari-tissuumaps
  summary: A plugin to add compatibility with Tissuumaps
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - npielawski
